services:
  app:
    build: .
    ports: 
      - "8000:8000"
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    depends_on:
      - ollama
    command: bash -c "bash /app/wait-for-model-download.sh && fastapi run main.py --port 8000"
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "ollama_entrypoint.sh"]


