services:
  app:
    build: .
    ports: 
      - "8000:8000"
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    depends_on:
      - ollama
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "ollama_entrypoint.sh"]


